### ISSUE TITLE
[BUG]Unable to connect to the raid server

### ISSUE THREAD

**Issue by wwng2333** [project-fika/Fika-Plugin#123]
**Describe the bug**
After upgrade fika-plugin from [Fika Release 0.9.8964.35784](https://github.com/project-fika/Fika-Plugin/releases/tag/v0.9.8964.35784) to [0.9.8980.39200](https://github.com/project-fika/Fika-Plugin/releases/tag/v0.9.8980.39200), when i start a raid it said unable to connect to the raid server. Then i downgrade to 0.9.8964 and it works fine.

**To Reproduce**
1.Start a raid
2. See error

**Screenshots**
![9da10cd81812c5b7a8a55482c88bb668](https://github.com/user-attachments/assets/2360f242-9d0b-4031-88b3-7329c27418e3)

**Log files**
[Player.log](https://github.com/user-attachments/files/16492259/Player.log)

**Desktop (please complete the following information):**
 - client Fika Version 0.9.8980.39200

**Comment by wwng2333** [comment]
> Your server is not getting the data. This is not a bug, rather incorrect configuration somewhere.

Thanks for reply, but i have no idea where to change the error cfg. Below is the fika.jsonc
```json
{
    "client": {
        "useBtr": true,
        "friendlyFire": false,
        "dynamicVExfils": false,
        "allowFreeCam": false,
        "allowItemSending": true,
        "blacklistedItems": [],
        "forceSaveOnDeath": false,
        "mods": {
            "required": [],
            "optional": []
        },
        "useInertia": true,
        "sharedQuestProgression": false
    },
    "server": {
        "giftedItemsLoseFIR": true,
        "launcherListAllProfiles": false,
        "sessionTimeout": 5,
        "showDevProfile": false,
        "showNonStandardProfile": false
    },
    "natPunchServer": {
        "enable": false,
        "port": 6790,
        "natIntroduceAmount": 1
    },
    "dedicated": {
        "profiles": {
            "amount": 0
        },
        "scripts": {
            "generate": true,
            "forceIp": ""
        }
    },
    "background": {
        "enable": true,
        "easteregg": false
    }
}
```

**Comment by Lacyway** [comment]
Try forcing your IPs in the F12 settings. It cannot detect them automatically.

**Comment by wwng2333** [comment]
> Try forcing your IPs in the F12 settings. It cannot detect them automatically.

![image](https://github.com/user-attachments/assets/6b505eb6-bc09-43eb-b5bc-0894fb19778b)
![image](https://github.com/user-attachments/assets/e64aaea9-3966-4b76-bcf1-4195e5ab67c5)

Already bind, but it still not work.

**Comment by Lacyway** [comment]
I assume you also updated your server mod? The issue is on that end then.

**Comment by wwng2333** [comment]
> I assume you also updated your server mod? The issue is on that end then.

Yep, server is already upgrade to 2.2.6, and when i start a raid, server reply error like this:
```
[Client Request] 192.168.20.8 \fika\raid\getsettings
TypeError: Cannot read properties of undefined (reading 'replace')
TypeError: Cannot read properties of undefined (reading 'replace')
    at HttpResponseUtil.clearString (C:\snapshot\src\utils\HttpResponseUtil.ts:18:14)
    at HttpResponseUtil.noBody (C:\snapshot\src\utils\HttpResponseUtil.ts:31:21)
    at FikaRaidCallbacks.handleRaidGetSettings (C:\Users\Administrator\Downloads\server\user\mods\fika-server\src\callbacks\FikaRaidCallbacks.ts:49:38)
    at RouteAction.action (C:\Users\Administrator\Downloads\server\user\mods\fika-server\src\routers\static\FikaRaidStaticRouter.ts:31:47)
    at FikaRaidStaticRouter.handleStatic (C:\snapshot\src\di\Router.ts:41:63)
    at HttpRouter.handleRoute (C:\snapshot\src\routers\HttpRouter.ts:61:68)
    at HttpRouter.getResponse (C:\snapshot\src\routers\HttpRouter.ts:34:36)
    at HttpRouter.getResponse (C:\Users\Administrator\Downloads\server\user\mods\fika-server\src\overrides\routers\HttpRouter.ts:25:63)
    at SptHttpListener.getResponse (C:\snapshot\src\servers\http\SptHttpListener.ts:130:44)
    at IncomingMessage.<anonymous> (C:\snapshot\src\servers\http\SptHttpListener.ts:64:49)
TypeError: Cannot read properties of undefined (reading 'replace')
TypeError: Cannot read properties of undefined (reading 'replace')
    at HttpResponseUtil.clearString (C:\snapshot\src\utils\HttpResponseUtil.ts:18:14)
    at HttpResponseUtil.noBody (C:\snapshot\src\utils\HttpResponseUtil.ts:31:21)
    at FikaRaidCallbacks.handleRaidGetSettings (C:\Users\Administrator\Downloads\server\user\mods\fika-server\src\callbacks\FikaRaidCallbacks.ts:49:38)
    at RouteAction.action (C:\Users\Administrator\Downloads\server\user\mods\fika-server\src\routers\static\FikaRaidStaticRouter.ts:31:47)
    at FikaRaidStaticRouter.handleStatic (C:\snapshot\src\di\Router.ts:41:63)
    at HttpRouter.handleRoute (C:\snapshot\src\routers\HttpRouter.ts:61:68)
    at HttpRouter.getResponse (C:\snapshot\src\routers\HttpRouter.ts:34:36)
    at HttpRouter.getResponse (C:\Users\Administrator\Downloads\server\user\mods\fika-server\src\overrides\routers\HttpRouter.ts:25:63)
    at SptHttpListener.getResponse (C:\snapshot\src\servers\http\SptHttpListener.ts:130:44)
    at IncomingMessage.<anonymous> (C:\snapshot\src\servers\http\SptHttpListener.ts:64:49)
```

**Comment by Lacyway** [comment]
You are trying to load SPT 3.9.5 which is not supported...

**Comment by wwng2333** [comment]
> You are trying to load SPT 3.9.5 which is not supported...

sorry for that, i have no idea which version is supported right now.
